### ISSUE TITLE
Question in Basic Usage

### ISSUE THREAD

**Issue by doerlbh** [scikit-tda/cechmate#9]
Hi there, 

I have a question regarding the Basic Usage in the Documentation.

In the example of cech diagram, what is the purpose of the "times two" operation? See attached:

dgmscech = cech.diagrams() * 2

BTW, there seems to be a typo in the doc, all the max_dim=1 should be maxdim=1 to prevent error.

Thanks!

**Comment by sauln** [comment]
Thanks for letting us know about the docs! We recently updated the API so it matches ripser.py. 

The x2 is so it can be directly comparable with Alpha filtrations since Cech uses radii while alpha uses diameter. @ctralie correct me if I’m wrong here.

We had talked at one point of scaling the alpha filtration, but haven’t made that happen yet.

Re the docs, a PR with fixes would be very helpful!

**Comment by doerlbh** [comment]
Thanks for the quick answer! Actually for the docs, the bug was only on the website example, the ipynb here is fine~

**Comment by ctralie** [comment]
Ah interesting, okay.  So we just need to propagate the docs.  And yes, the
x2 is because rips filtration is usually specified in edge length between
two points, which is akin to a diameter, while alpha and cech are expressed
in radius
